Update README.md
PAD1K/code-practice pull request #17
Opened 2024-01-09 07:18 UTC by Wacko34

Начал работу над движением

2024-01-09 18:25 UTC, HozzyUwU requested changes

2024-01-09 18:25 UTC, HozzyUwU commented on Assets/CameraTracker.cs
> +    private Transform player;
Не сходится с код стайлом, необходимо отформатировать,

2024-01-09 18:25 UTC, HozzyUwU commented on Assets/CameraTracker.cs
> +        player = GameObject.FindGameObjectWithTag("Player").transform;
В 99% нет смысла использовать Find, является плохой практикой. Альтернативный вариант возможно создать с помощью [сериализации](https://docs.unity3d.com/ScriptReference/SerializeField.html) или TryGetComponent/GetComponent.

2024-01-09 18:25 UTC, HozzyUwU commented on Assets/CameraTracker.cs
> +        Vector3 newPosition = transform.position;
Не используй лишний раз память, можно написать transform.position = player.position

2024-01-09 18:25 UTC, HozzyUwU commented on Assets/CameraTracker.cs
> +        transform.position = newPosition;
Нет повода отдельно присваивать x и y, работай с векторами.

2024-01-09 18:25 UTC, HozzyUwU commented on Assets/CharacterController2D.cs
> +	public UnityEvent OnLandEvent;
Для обучения и интеграции с Unity едитором супер, но на практике всегда используй C# ивенты. Нужно переписать.

2024-01-09 18:25 UTC, HozzyUwU commented on Assets/PlayerMovement.cs
> +        } else if (Input.GetButtonUp("Crouch")) {
Реализация представлена для старой системы распознавания инпута, необходимо переписать под [новую](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.7/manual/index.html).

2024-01-10 18:33 UTC, Wacko34 commented on Assets/PlayerMovement.cs
> +        } else if (Input.GetButtonUp("Crouch")) {
Я переписал, но мне не очень нравится то, что я нагромоздил if else

2024-01-10 21:31 UTC, HozzyUwU approved these changes

2024-01-10 21:31 UTC, merged