29 add user UI
PAD1K/code-practice pull request #32
Opened 2024-01-15 18:37 UTC by Wacko34

2024-01-17 11:14 UTC, HozzyUwU requested changes
Не обратил внимание по коду, но Unity мне показало, что у тебя есть неиспользуемые переменные, стоит убрать.
![image](https://github.com/PAD1K/code-practice/assets/82671681/1deb0070-cef7-49ae-8374-767205f9f4b0)

2024-01-17 11:14 UTC, HozzyUwU commented on Assets/Scripts/Enemy/Enemy.cs
> +        player.GetComponent<PlayerExperience>().AddXp(1);
Отказывайся от Find и подобных методов, в данном случае ни на что не повлияет, но практика негативная.

2024-01-17 11:14 UTC, HozzyUwU commented on Assets/Scripts/Player/PlayerExperience.cs
> +    private int _level = 0;
Вряд ли что то из этого у тебя принимает отрицательные числа, сразу выбирай подходящий тип данных, например uint.

2024-01-17 11:14 UTC, HozzyUwU commented on Assets/Scripts/Player/PlayerMovement.cs
> +    }
Старайся сделать классы максимально изолированными, переработай логику, чтобы set вообще не требовался.

2024-01-17 11:14 UTC, HozzyUwU commented on Assets/Scripts/Player/PlayerMovement.cs
>              _isAcceleration = false;
Не забывай про фигурные скобки)

2024-01-17 11:14 UTC, HozzyUwU commented on Assets/Scripts/Player/PlayerMovement.cs
> +            }
Видишь как у тебя расширяется Update с каждым разом, вынеси все в функции, в идеале в Update должны быть только вызовы.

2024-01-17 11:14 UTC, HozzyUwU commented on Assets/Scripts/UI/StaminaBar.cs
> +}
Точно нет, зачем нам принципы ООП, если мы дублируем один и тот же код для каждой задачи.

2024-01-17 11:14 UTC, HozzyUwU commented on Assets/Scripts/UI/XpBar.cs
> +}
Будем струячить один и тот же код для каждого нового бара?)

2024-01-17 20:14 UTC, Wacko34 commented on Assets/Scripts/UI/XpBar.cs
> +}
Вообще я думал как вынести все в один класс, но по итогу ничего нормального не придумал, еще подумаю

2024-01-18 19:26 UTC, Wacko34 commented on Assets/Scripts/Enemy/Enemy.cs
> +        player.GetComponent<PlayerExperience>().AddXp(1);
Можно, пожалуйста, подсказку, как переделать без Find. Он мне тоже не особо понравился, но как сделать без него я не придумал.

2024-01-18 20:15 UTC, Wacko34 commented on Assets/Scripts/UI/XpBar.cs
> +}
Вот смотри, я выделил класс Bar, где сделал поле _slider, конструктор и методы для установки/изменения значения. Работаю над HealthBar: оставил у него только конструктор, куда передается slider. Каким образом я могу это использовать? 

Ну типа я не понимаю как мне теперь назначить свой слайдер на HeathBar, как его правильно инициализировать и как мне теперь это все дело использовать.

2024-01-19 18:47 UTC, HozzyUwU commented on Assets/Scripts/Enemy/Enemy.cs
> +        player.GetComponent<PlayerExperience>().AddXp(1);
Самое банальное - прямая ссылка на объект класса PlayerExperience, альтерантивным является возможность реализации singleton или static метода

2024-01-19 18:48 UTC, HozzyUwU commented on Assets/Scripts/UI/XpBar.cs
> +}
@Wacko34 на созвоне это разберем

2024-01-20 08:31 UTC, Wacko34 commented
@HozzyUwU Можно проверять

2024-01-20 20:08 UTC, HozzyUwU approved these changes

2024-01-20 20:08 UTC, merged